# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: filips.FirefoxPWA
PackageVersion: 2.10.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x86
AppsAndFeaturesEntries:
- UpgradeCode: '{E1CD921B-369E-47CB-AD2E-3BCA94142512}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/filips123/PWAsForFirefox/releases/download/v2.10.0/firefoxpwa-2.10.0-x86.msi
  InstallerSha256: 44CC4B84BE8B762B9391960B31EB8A74805B13842D03AD2540768D78B97B4453
  ProductCode: '{C24A98C3-F09B-4DC7-B908-63A5DBE1E5DA}'
- Architecture: x64
  InstallerUrl: https://github.com/filips123/PWAsForFirefox/releases/download/v2.10.0/firefoxpwa-2.10.0-x86_64.msi
  InstallerSha256: 5E8285D7BD8E8DF35CFC286FFD65E42BAE40722CC1B0693977F1A9CB8968A5D1
  ProductCode: '{8180F05A-39E8-4468-A00F-83A174667E53}'
ManifestType: installer
ManifestVersion: 1.5.0
